package com.softdesign.devintensive.data.storage.models;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIKES".
*/
public class LikeListDao extends AbstractDao<LikeList, Long> {

    public static final String TABLENAME = "LIKES";

    /**
     * Properties of entity LikeList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserRemoteId = new Property(1, String.class, "userRemoteId", false, "USER_REMOTE_ID");
        public final static Property UserLikeRemoteId = new Property(2, String.class, "userLikeRemoteId", false, "USER_LIKE_REMOTE_ID");
    };

    private DaoSession daoSession;

    private Query<LikeList> user_LikesByQuery;

    public LikeListDao(DaoConfig config) {
        super(config);
    }
    
    public LikeListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIKES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_REMOTE_ID\" TEXT NOT NULL ," + // 1: userRemoteId
                "\"USER_LIKE_REMOTE_ID\" TEXT);"); // 2: userLikeRemoteId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIKES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LikeList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserRemoteId());
 
        String userLikeRemoteId = entity.getUserLikeRemoteId();
        if (userLikeRemoteId != null) {
            stmt.bindString(3, userLikeRemoteId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LikeList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserRemoteId());
 
        String userLikeRemoteId = entity.getUserLikeRemoteId();
        if (userLikeRemoteId != null) {
            stmt.bindString(3, userLikeRemoteId);
        }
    }

    @Override
    protected final void attachEntity(LikeList entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LikeList readEntity(Cursor cursor, int offset) {
        LikeList entity = new LikeList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // userRemoteId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // userLikeRemoteId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LikeList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserRemoteId(cursor.getString(offset + 1));
        entity.setUserLikeRemoteId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LikeList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LikeList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "likesBy" to-many relationship of User. */
    public List<LikeList> _queryUser_LikesBy(String userRemoteId) {
        synchronized (this) {
            if (user_LikesByQuery == null) {
                QueryBuilder<LikeList> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserRemoteId.eq(null));
                user_LikesByQuery = queryBuilder.build();
            }
        }
        Query<LikeList> query = user_LikesByQuery.forCurrentThread();
        query.setParameter(0, userRemoteId);
        return query.list();
    }

}
